Add options
iliana/emojos.in pull request #12
Opened 2019-07-15 10:59 UTC by yingziwu

Add option to see unlisted emojos
Add option to see animated emojos (fix  #10 )

2019-07-15 20:48 UTC, iliana requested changes
I'll test this at home tonight, but right now I have a few requests:

(also thank you so much for this!)

2019-07-15 20:48 UTC, iliana commented on .gitignore
> +# Edit at https://www.gitignore.io/?templates=python
Can you drop the .gitignore change from this PR? A significant amount of this is unnecessary.

2019-07-15 20:48 UTC, iliana commented on emojos.py
> +    if request.args.get('filter_all','') == 'on':
Can you run a style linter? I believe it will require a space after the comma here.

2019-08-27 06:36 UTC, yingziwu commented
Can you merge this PR?

2019-08-28 23:32 UTC, merged